

[build-system]
requires=["setuptools"]
build-backend="setuptools.build_meta"


[project]
name="pixelator"
dependencies=["Pillow"]
dynamic=["version"]

[project.scripts]
pixelator="pixelator.__main__:main"

[tool.setuptools.dynamic]
version = {attr = 'pixelator.__version__'}
